# Generated by Django 5.2.17 on 2026-09-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinicalencounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalencounter',
            name='bp_diastolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diastolic BP'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='bp_systolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Systolic BP'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heart Rate (BPM)'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='o2_saturation',
            field=models.IntegerField(blank=True, null=True, verbose_name='O2 Saturation %'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
